version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - server
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
  
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:80
    networks:
      - server
    depends_on:
      - backend
    expose:
      - 3000

networks:
  server:
    driver: bridge

